import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { ReactNode } from 'react';

import Footer from '@/components/footer';
import LayoutBg from '@/components/layout-bg/layout-bg';
import Navbar from '@/components/navbar/navbar';

import './globals.scss';
import styles from './page.module.scss';

export const metadata: Metadata = {
    title: 'Serhat Belen',
    description: 'Generated by create next app',
};

const poppins = Poppins({
    weight: '400',
    subsets: ['latin'],
});

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const [messages, locale] = await Promise.all([getMessages(), getLocale()]);

    return (
        <html lang={locale}>
            <body className={poppins.className}>
                <LayoutBg />
                <AppRouterCacheProvider>
                    <NextIntlClientProvider messages={messages}>
                        <Navbar />
                        <main className={styles.main}>{children}</main>
                        <Footer />
                    </NextIntlClientProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
